#%RAML 1.0 Library
usage: Defines entities used in the Portal Experience API
types:
  ContactType:
    usage: Creates the enum of contact types   
    type: string
    enum: ["store_customer", "donor", "fundrive_user"]
  ContactProfile:
    usage: Defines the Contact Profile
    type: object
    displayName: Contact Profile
    description: Defines data elements that comprise a contact profile
    properties:
      id:
        type: number
        required: false
        minimum: 1
        description: Contact Id
        displayName: Id
      email:
        type: string
        required: true
        description: Email address
        displayName: Email
        pattern: ^\w+@[a-zA-Z_]+?.[a-zA-Z]{2,3}$
      first_name:
        type: string
        description: First name
      last_name:
        type: string
        description: Last name
      phone:
        type: string
        required: true
        description: Primary phone
        pattern: ^[0-9]{10}$
        example: "1234567892"
      postal_code:
        type: string
        required: true
        description: Postal Code
      ok_to_send_text:
        type: boolean
        default: false
        required: false
        description: Okay to send texts to this contact
      preferred_store:
        type: number
        required: false
        description: Preferred store for contact
        minimum: 1000
        maximum: 9999
      mobile_number:
        type: string
        required: false
        description: Mobile phone for texting
        pattern: ^[0-9]{10}$
        example: "1234567890"
      date_of_birth:
        type: string
        pattern: ^(0[1-9]|1[0-2])\/(0[1-9]|1\d|2\d|3[01])\/(19|20)\d{2}$
        required: false
        description: Contact DOB
        example: "08/06/1963"
  ContactProfileResponse:
    type: ContactProfile
    properties:
      contact_types: 
        items: ContactType
        type: ContactType[]
        required: true
      allow_emails:
        type: boolean
        required: true
  ContactProfileMessage: 
      type: object
      properties:
        message:
          required: true
          type: string
        success:
          required: true
          type: boolean
        status:
          required: true
          type: number
        data?:
          type: ContactProfileResponse
          displayName: Contact Profile Data
          description: The contact profile retrieved
  PostalCodeProfile:
    type: object
    properties:
      PostalCode:
        type: string
      Country:
        type: string | nil
      State:
        type: string | nil
  PostalCodeValidationResponse:
    type: object
    properties:
      message:
        type: string
        displayName: Result message
      status:
        type: number
      success:
        type: boolean
	  apistatus
		type: string
      data?:
        type: PostalCodeProfile 
        required: false
        
      
