#%RAML 1.0 ExampleSpec
|
{
  "postalcode": "4875",
  "country": "AU",
  "state": "QLD",
  "city": "Thursday Island",
  "location": {
    "lat": -10.5799693,
    "lng": 142.2193697
  },
  "localities": [
    "Boigu Island",
    "Dauan Island",
    "Iama Island",
    "Mabuiag Island",
    "Moa Island",
    "Poruma Island",
    "Prince of Wales",
    "Saibai Island",
    "Thursday Island",
    "Warraber Islet"
  ],
  "formattedaddress": "Thursday Island QLD 4875, Australia"
}
